include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SwipeSelectionPrefs
SwipeSelectionPrefs_FILES = SSRootListController.m ../SSPreferences.m
SwipeSelectionPrefs_FRAMEWORKS = UIKit Foundation CoreFoundation
SwipeSelectionPrefs_PRIVATE_FRAMEWORKS = Preferences
SwipeSelectionPrefs_INSTALL_PATH = /Library/PreferenceBundles
SwipeSelectionPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
